apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${project.artifactId}-deployment
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: ${project.artifactId}
  template:
    metadata:
      labels:
        app: ${project.artifactId}
    spec:
      containers:
      - name: ${project.artifactId}
        image: soprasteria/fsservice:${project.version}